import * as stylex from '@stylexjs/stylex';
import { colors } from '@lody/ui/tokens/colors.stylex';
import { radius, space, text } from '@lody/ui/tokens/scales.stylex';
import { conversation } from './conversation.tokens.stylex';

export const conversationSurface = stylex.create({
  message: { paddingBlock: conversation.messagePadding },
  userMessage: { paddingTop: 0, paddingBottom: conversation.responseGap },
  firstRow: { paddingTop: 0 },
  proseRow: { paddingTop: conversation.proseGap, paddingBottom: 0 },
  surfaceRow: { paddingTop: conversation.surfaceGap, paddingBottom: 0 },
  processRow: { paddingBlock: 0 },
  footerRow: { paddingBlock: 0 },
  lastRow: { paddingBottom: conversation.messagePadding },
  // Next-user metadata and footer actions share the round reserve. Taller
  // file cards or wrapped actions grow naturally beyond this minimum.
  roundFooter: {
    minHeight: `max(0px, calc(${conversation.roundGap} - ${conversation.metadataPitch} - ${conversation.metadataGap}))`,
  },
  roundFooterRow: { paddingBottom: 0 },
  roundLastRow: {
    paddingBottom: `max(0px, calc(${conversation.roundGap} - ${conversation.metadataPitch} - ${conversation.metadataGap}))`,
  },
  processText: {
    fontSize: text.subheadlineSize,
    lineHeight: text.subheadlineLeading,
    fontWeight: 400,
    color: colors.secondaryLabel,
  },
  processLine: {
    display: 'flex',
    width: '100%',
    minHeight: conversation.activityPitch,
    alignItems: 'center',
    columnGap: space[1.5],
    paddingBlock: conversation.activityPadding,
    paddingInline: conversation.railInset,
    color: colors.secondaryLabel,
  },
  step: {
    width: 'fit-content',
    maxWidth: '100%',
    alignItems: 'flex-start',
    minHeight: conversation.activityPitch,
    paddingBlock: conversation.activityPadding,
    paddingInline: conversation.railInset,
    borderRadius: radius.mini,
    userSelect: 'none',
  },
  collapsible: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    columnGap: space[1.5],
    borderRadius: radius.mini,
    paddingInline: space[1],
    paddingBlock: space[1],
    textAlign: 'start',
    color: { default: colors.secondaryLabel, ':hover': colors.label },
  },
  flushCollapsible: { paddingInline: 0 },
  disclosure: {
    display: 'flex',
    width: '100%',
    minHeight: conversation.activityPitch,
    alignItems: 'center',
    columnGap: `calc(${space[1]} / 2)`,
    paddingBlock: conversation.activityPadding,
    paddingInline: conversation.railInset,
    color: colors.secondaryLabel,
    textAlign: 'start',
  },
  mobileDisclosure: {
    columnGap: space[1.5],
    borderRadius: radius.mini,
    backgroundColor: { default: 'transparent', ':hover': conversation.activityHoverFill },
  },
  processStep: {
    display: 'flex',
    width: '100%',
    minHeight: conversation.activityPitch,
    alignItems: 'flex-start',
    columnGap: space[1.5],
    paddingBlock: conversation.activityPadding,
    paddingInline: conversation.railInset,
  },
  userRow: { display: 'flex', width: '100%', flexDirection: 'row-reverse', columnGap: space[2] },
  mobileUserRow: { paddingLeft: '28px' },
  author: {
    flexShrink: 0,
    color: colors.secondaryLabel,
    paddingTop: `calc(${conversation.metadataPitch} + ${conversation.metadataGap} + ${conversation.bubblePaddingBlock} + (${conversation.readingLeading} - ${space[8]}) / 2)`,
  },
  userStack: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-end',
    rowGap: conversation.metadataGap,
    textAlign: 'start',
    maxWidth: {
      default: '100%',
      '@container (min-width: 520px)': '80%',
      '@container (min-width: 720px)': '70%',
    },
  },
  mobileUserStack: { maxWidth: 'min(100%, 28rem)' },
  metadata: {
    display: 'flex',
    minHeight: conversation.metadataPitch,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    columnGap: space[1.5],
    color: colors.secondaryLabel,
    fontSize: text.captionSize,
    lineHeight: text.captionLeading,
  },
  userActions: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: conversation.metadataGap,
    display: 'flex',
    columnGap: `calc(${space[1]} / 2)`,
  },
  attachments: {
    display: 'flex',
    minWidth: 0,
    maxWidth: '100%',
    flexDirection: 'column',
    alignItems: 'flex-end',
    rowGap: space[2],
  },
  bubbleRow: { display: 'flex', maxWidth: '100%', justifyContent: 'flex-end' },
  bubble: {
    minWidth: 0,
    maxWidth: '100%',
    borderRadius: conversation.bubbleRadius,
    backgroundColor: conversation.bubbleFill,
    paddingInline: conversation.bubblePaddingInline,
    paddingBlock: conversation.bubblePaddingBlock,
  },
  userText: {
    minWidth: 0,
    maxWidth: '100%',
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    color: conversation.reading,
  },
  collapsed: { overflow: 'hidden' },
  expand: {
    marginTop: space[1],
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
});
